services:
  backend:
    env_file: []
    environment:
      APP_NAME: Skedway
      APP_ENV: testing
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "true"
      APP_URL: http://localhost

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app

      CACHE_DRIVER: file
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync

      REDIS_HOST: redis
      REDIS_PORT: "6379"

  db:
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root