services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: unless-stopped

  backend:
    image: ghcr.io/<seu-usuario-github>/skedway-backend:latest
    restart: unless-stopped
    env_file:
      - /opt/app/backend.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/skedway-event-management/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ubuntu/skedway-event-management/backend/public:/var/www/html/public:ro
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew --webroot -w /var/www/certbot; done'

volumes:
  dbdata:
  letsencrypt:
  certbot_www:
