name: backend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  php:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: app
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3307:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot || exit 1"
          --health-interval=5s --health-timeout=5s --health-retries=10
      redis:
        image: redis:7
        ports:
          - "6379:6379"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, redis
          coverage: none

      - name: Install deps
        working-directory: backend
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Create .env for CI
        working-directory: backend
        run: |
          cp .env.example .env
          sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/^DB_PORT=.*/DB_PORT=3307/' .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=app/' .env
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=app/' .env
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=app/' .env
          sed -i 's/^REDIS_HOST=.*/REDIS_HOST=127.0.0.1/' .env
          php artisan key:generate --force
          php -r "for(\$i=0;\$i<20;\$i++){try{new PDO('mysql:host=127.0.0.1;port=3307;dbname=app','app','app');exit(0);}catch(Throwable \$e){sleep(3);} } exit(1);"

      - name: Migrate
        working-directory: backend
        run: php artisan migrate --force

      - name: Tests
        working-directory: backend
        run: php vendor/bin/phpunit --testdox

      - name: Lint (Pint)
        working-directory: backend
        run: php vendor/bin/pint --test