name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (Laravel + Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate APP_KEY for CI
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" >> "$GITHUB_ENV"

      - name: Start containers (CI override)
        run: |
          docker version
          docker compose version
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build db backend
          docker compose ps

      - name: Prepare Laravel (composer, key, migrate)
        run: |
          docker compose exec -T backend composer install --no-interaction --prefer-dist --no-progress
          docker compose exec -T backend php artisan key:generate || true
          for i in {1..20}; do
            if docker compose exec -T backend php -r "try { new PDO('mysql:host='.(getenv('DB_HOST')?:'db').';port='.(getenv('DB_PORT')?:'3306'), getenv('DB_USERNAME')?:'app', getenv('DB_PASSWORD')?:'app'); echo 'ok'; } catch (Throwable $e) { exit(1);}"; then
              echo 'DB ready'; break
            fi
            echo 'Waiting DB...'; sleep 3
          done
          docker compose exec -T backend php artisan migrate --force || true

      - name: PHP Style (Pint)
        run: docker compose exec -T backend php vendor/bin/pint --test

      - name: PHP Unit
        run: docker compose exec -T backend php vendor/bin/phpunit --testdox

      - name: Teardown
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v

  frontend:
    name: Frontend (Vite/React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Upload dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist